import './globals.css'
import Head from 'next/head'

export const metadata = {
  title: 'Reservation',
  description: 'Generated by Mohammadreza'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <Head>
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1, maximum-scale=1'
        />
      </Head>
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
